### ISSUE TITLE
Add Bubble sort algorithm visualizer

### ISSUE THREAD

**Issue by amit-y11** [amit-y11/sorting-algorithm-visualizer#1]
add a code for bubble sort algorithm visualizer

**Comment by bharati-21** [comment]
Hi,
I'd like to work on this as a part of Hacktoberfest '21!
Thank you.

**Comment by amit-y11** [comment]
sure, you can work on this

**Comment by amit-y11** [comment]
@bharati-21 any updates?

**Comment by bharati-21** [comment]
> @bharati-21 any updates?

Yes, I have started working on this. Working on the UI of this right now. 
Most probably will be done by the start of next week. 👍🏽

**Comment by amit-y11** [comment]
okay no problem, take your time

**Comment by bharati-21** [comment]
> okay no problem, take your time

I've created a PR. Kindly review.

A feedback I had was that the visualizer can be made simpler by showing the numbers below the `div.poles` for users to visualize the numbers along with the swap. 👍🏽

**Comment by amit-y11** [comment]
> A feedback I had was that the visualizer can be made simpler by showing the numbers below the `div.poles` for users to visualize the numbers along with the swap. 👍🏽

Thanks for the feedback @bharati-21, I will surely consider this 😊
